---
# file: playbooks/prepare.yml

- hosts: deck
  tasks:
    - name: Testing
      debug:
        msg: Testing Preparation

# Check expected variables are defined
# Change root password
# Change user password
# Add user to sudoers group
# Create expected folder paths

    - name: Installing Flatpaks
      flatpak:
        name:
          - flathub me.kozec.syncthingtk